#include<iostream>
#include<stdio.h>
using namespace std;
class emp{
	public:
	int emp_id;
	char emp_name[50];
	char emp_role[50];
	int emp_age;
	int emp_salary;
	int emp_experience;
	char emp_city[50];
	char emp_company_name[50];	
};
int main(){
	emp obj1;
	obj1.emp_id;
	obj1.emp_name;
	obj1.emp_role;
	obj1.emp_age;
	obj1.emp_salary;
	obj1.emp_experience;
	obj1.emp_city;
	obj1.emp_company_name;
	cout<<"=> Enter 1st emp's details::"<<endl;	
	cout<<"Enter emp's id :";
	cin>>obj1.emp_id;
	cout<<"Enter emp's name :";
	cin>>obj1.emp_name;
	cout<<"Enter emp's role :";
	cin>>obj1.emp_role;
	cout<<"Enter emp's age :";
	cin>>obj1.emp_age;
	cout<<"Enter emp's salary :";
	cin>>obj1.emp_salary;
	cout<<"Enter emp's experience :";
	cin>>obj1.emp_experience;
	cout<<"Enter emp's city :";
	cin>>obj1.emp_city;
	cout<<"Enter emp's company name :";
	cin>>obj1.emp_company_name;
	cout<<endl;
	
	emp obj2;
	obj2.emp_id;
	obj2.emp_name;
	obj2.emp_role;
	obj2.emp_age;
	obj2.emp_salary;
	obj2.emp_experience;
	obj2.emp_city;
	obj2.emp_company_name;
	cout<<"=> Enter 2nd emp's details::"<<endl;	
	cout<<"Enter emp's id :";
	cin>>obj2.emp_id;
	cout<<"Enter emp's name :";
	cin>>obj2.emp_name;
	cout<<"Enter emp's role :";
	cin>>obj2.emp_role;
	cout<<"Enter emp's age :";
	cin>>obj2.emp_age;
	cout<<"Enter emp's salary :";
	cin>>obj2.emp_salary;
	cout<<"Enter emp's experience :";
	cin>>obj2.emp_experience;
	cout<<"Enter emp's city :";
	cin>>obj2.emp_city;
	cout<<"Enter emp's company name :";
	cin>>obj2.emp_company_name;
	cout<<endl;
	
	emp obj3;
	obj3.emp_id;
	obj3.emp_name;
	obj3.emp_role;
	obj3.emp_age;
	obj3.emp_salary;
	obj3.emp_experience;
	obj3.emp_city;
	obj3.emp_company_name;
	cout<<"=> Enter 3rd emp's details::"<<endl;	
	cout<<"Enter emp's id :";
	cin>>obj3.emp_id;
	cout<<"Enter emp's name :";
	cin>>obj3.emp_name;
	cout<<"Enter emp's role :";
	cin>>obj3.emp_role;
	cout<<"Enter emp's age :";
	cin>>obj3.emp_age;
	cout<<"Enter emp's salary :";
	cin>>obj3.emp_salary;
	cout<<"Enter emp's experience :";
	cin>>obj3.emp_experience;
	cout<<"Enter emp's city :";
	cin>>obj3.emp_city;
	cout<<"Enter emp's company name :";
	cin>>obj3.emp_company_name;
	cout<<endl;
	
	emp obj4;
	obj4.emp_id;
	obj4.emp_name;
	obj4.emp_role;
	obj4.emp_age;
	obj4.emp_salary;
	obj4.emp_experience;
	obj4.emp_city;
	obj4.emp_company_name;
	cout<<"=> Enter 4th emp's details::"<<endl;	
	cout<<"Enter emp's id :";
	cin>>obj4.emp_id;
	cout<<"Enter emp's name :";
	cin>>obj4.emp_name;
	cout<<"Enter emp's role :";
	cin>>obj4.emp_role;
	cout<<"Enter emp's age :";
	cin>>obj4.emp_age;
	cout<<"Enter emp's salary :";
	cin>>obj4.emp_salary;
	cout<<"Enter emp's experience :";
	cin>>obj4.emp_experience;
	cout<<"Enter emp's city :";
	cin>>obj4.emp_city;
	cout<<"Enter emp's company name :";
	cin>>obj4.emp_company_name;
	cout<<endl;
	
	emp obj5;
	obj5.emp_id;
	obj5.emp_name;
	obj5.emp_role;
	obj5.emp_age;
	obj5.emp_salary;
	obj5.emp_experience;
	obj5.emp_city;
	obj5.emp_company_name;
	cout<<"=> Enter 5th emp's details::"<<endl;	
	cout<<"Enter emp's id :";
	cin>>obj5.emp_id;
	cout<<"Enter emp's name :";
	cin>>obj5.emp_name;
	cout<<"Enter emp's role :";
	cin>>obj5.emp_role;
	cout<<"Enter emp's age :";
	cin>>obj5.emp_age;
	cout<<"Enter emp's salary :";
	cin>>obj5.emp_salary;
	cout<<"Enter emp's experience :";
	cin>>obj5.emp_experience;
	cout<<"Enter emp's city :";
	cin>>obj5.emp_city;
	cout<<"Enter emp's company name :";
	cin>>obj5.emp_company_name;
	cout<<endl;
	
	cout<<"=>1st emp's details:"<<endl;	
	cout<<"emp's id is :"<<obj1.emp_id<<endl;
	cout<<"emp's name is :"<<obj1.emp_name<<endl;
	cout<<"emp's role is :"<<obj1.emp_role<<endl;
	cout<<"emp's age is :"<<obj1.emp_age<<endl;
	cout<<"emp's salary is :"<<obj1.emp_salary<<endl;
	cout<<"emp's experience is :"<<obj1.emp_experience<<endl;
	cout<<"emp's city is :"<<obj1.emp_city<<endl;
	cout<<"emp's company name is :"<<obj1.emp_company_name<<endl<<endl;
	cout<<"=>2nd emp's details:"<<endl;	
	cout<<"emp's id is :"<<obj2.emp_id<<endl;
	cout<<"emp's name is :"<<obj2.emp_name<<endl;
	cout<<"emp's role is :"<<obj2.emp_role<<endl;
	cout<<"emp's age is :"<<obj2.emp_age<<endl;
	cout<<"emp's salary is :"<<obj2.emp_salary<<endl;
	cout<<"emp's experience is :"<<obj2.emp_experience<<endl;
	cout<<"emp's city is :"<<obj2.emp_city<<endl;
	cout<<"emp's company name is :"<<obj2.emp_company_name<<endl<<endl;
	cout<<"=>3rd emp's details:"<<endl;	
	cout<<"emp's id is :"<<obj3.emp_id<<endl;
	cout<<"emp's name is :"<<obj3.emp_name<<endl;
	cout<<"emp's role is :"<<obj3.emp_role<<endl;
	cout<<"emp's age is :"<<obj3.emp_age<<endl;
	cout<<"emp's salary is :"<<obj3.emp_salary<<endl;
	cout<<"emp's experience is :"<<obj3.emp_experience<<endl;
	cout<<"emp's city is :"<<obj3.emp_city<<endl;
	cout<<"emp's company name is :"<<obj3.emp_company_name<<endl<<endl;
	cout<<"=>4th emp's details:"<<endl;	
	cout<<"emp's id is :"<<obj4.emp_id<<endl;
	cout<<"emp's name is :"<<obj4.emp_name<<endl;
	cout<<"emp's role is :"<<obj4.emp_role<<endl;
	cout<<"emp's age is :"<<obj4.emp_age<<endl;
	cout<<"emp's salary is :"<<obj4.emp_salary<<endl;
	cout<<"emp's experience is :"<<obj4.emp_experience<<endl;
	cout<<"emp's city is :"<<obj4.emp_city<<endl;
	cout<<"emp's company name is :"<<obj4.emp_company_name<<endl<<endl;
	cout<<"=>5th emp's details:"<<endl;	
	cout<<"emp's id is :"<<obj5.emp_id<<endl;
	cout<<"emp's name is :"<<obj5.emp_name<<endl;
	cout<<"emp's role is :"<<obj5.emp_role<<endl;
	cout<<"emp's age is :"<<obj5.emp_age<<endl;
	cout<<"emp's salary is :"<<obj5.emp_salary<<endl;
	cout<<"emp's experience is :"<<obj5.emp_experience<<endl;
	cout<<"emp's city is :"<<obj5.emp_city<<endl;
	cout<<"emp's company name is :"<<obj5.emp_company_name<<endl<<endl;
	return 0;
}
